
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 26 16:16:18 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 24;
  public static final int GE = 17;
  public static final int UMINUS = 39;
  public static final int BRALEFT = 37;
  public static final int LPAREN = 25;
  public static final int SEMI = 27;
  public static final int REPEAT = 6;
  public static final int INT = 28;
  public static final int FOR = 31;
  public static final int MINUS = 22;
  public static final int WRITE = 9;
  public static final int RPAREN = 26;
  public static final int AND = 19;
  public static final int LT = 14;
  public static final int OR = 20;
  public static final int COMMA = 30;
  public static final int BEGIN = 32;
  public static final int UNTIL = 7;
  public static final int NUM = 11;
  public static final int PLUS = 21;
  public static final int ASSIGN = 12;
  public static final int IF = 2;
  public static final int ID = 10;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int RETURN = 33;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int VOID = 34;
  public static final int EQ = 13;
  public static final int TIMES = 23;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int THEN = 3;
  public static final int NE = 18;
  public static final int BRARIGHT = 38;
  public static final int END = 5;
  public static final int FALSE = 35;
  public static final int GT = 15;
}

