
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 08 21:17:07 PYT 2016
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 22;
  public static final int OVER = 40;
  public static final int GE = 35;
  public static final int PUN = 49;
  public static final int BRALEFT = 43;
  public static final int INTEGER = 8;
  public static final int SEMI = 46;
  public static final int LPAREN = 41;
  public static final int REPEAT = 6;
  public static final int ARRAY = 47;
  public static final int MINUS = 38;
  public static final int FOR = 26;
  public static final int WRITE = 16;
  public static final int RPAREN = 42;
  public static final int AND = 25;
  public static final int LT = 32;
  public static final int OR = 27;
  public static final int COMMA = 45;
  public static final int BEGIN = 28;
  public static final int UNTIL = 13;
  public static final int NUM = 18;
  public static final int PLUS = 37;
  public static final int ASSIGN = 30;
  public static final int IF = 2;
  public static final int ID = 17;
  public static final int LE = 34;
  public static final int OF = 50;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 14;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int PROGRAM = 21;
  public static final int EQ = 31;
  public static final int TIMES = 39;
  public static final int PUNTOS = 24;
  public static final int ELSE = 4;
  public static final int READ = 15;
  public static final int TO = 12;
  public static final int WHILE = 7;
  public static final int THEN = 3;
  public static final int NE = 36;
  public static final int BRARIGHT = 44;
  public static final int END = 5;
  public static final int FALSE = 19;
  public static final int DT = 11;
  public static final int GT = 33;
  public static final int VAR = 29;
  public static final int PROCEDURE = 23;
  public static final int DO = 10;
  public static final int PU = 48;
}

